### ISSUE TITLE
Building project with Urho.Forms in release mode

### ISSUE THREAD

**Issue by MichalPetryk** [xamarin/urho#110]
When i'm trying to build sample project "FormsSample.Droid" in release mode and Linking is set to "Sdk Assemblies Only", i got an error:

> Severity Code Description Project File Line Suppression State
Error The "LinkAssemblies" task failed unexpectedly.
Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item '!!0[] System.Array::Empty()' (defined in 'Urho.Forms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') from 'Urho.Forms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve !!0[] System.Array::Empty()
at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
at Mono.Linker.Steps.MarkStep.ProcessQueue()
at Mono.Linker.Steps.MarkStep.Process()
at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
at Mono.Linker.Pipeline.Process(LinkContext context)
at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
at Xamarin.Android.Tasks.LinkAssemblies.Execute()
--- End of inner exception stack trace ---
at Xamarin.Android.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
at Xamarin.Android.Tasks.LinkAssemblies.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext() FormsSample.Droid

When linking is set to "None" everything works perfectly but generated *.apk file is really big.

**Comment by EgorBo** [comment]
@MichalPetryk It's a known issue. Should be fixed in the next nuget update. Also I'd recomend to use "generate APK per ABI" option cause UrhoSharp has 5 native libs - ~7-14mb each.

**Comment by MichalPetryk** [comment]
@EgorBo thank you very much for your help!

**Comment by ggirard07** [comment]
@EgorBo I am seeing this issue in my own Android binding project but cannot find any info about it anywhere...

Could you please elaborate on the fix? Do you have any reference to some documentation or commit ids to help me understand what is happening?
