### ISSUE TITLE
Calling UrhoSurface.Run<T>() on UWP throws an exception

### ISSUE THREAD

**Issue by thargy** [xamarin/urho#117]
Calling Run without providing the location of an asset pack (or supplying the default null) throws an exception:

```
System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=Urho
  StackTrace:
       at Urho.Application.Application_Run(IntPtr handle)
       at Urho.Application.Run()
       at Urho.UWP.UrhoSurface.Run(Type appType, String customAssetsPak)
       at Urho.UWP.UrhoSurface.Run[TGame](String customAssetsPak)
       at Universal.MainPage..ctor()
       at Universal.Universal_XamlTypeInfo.XamlTypeInfoProvider.Activate_3_MainPage()
       at Universal.Universal_XamlTypeInfo.XamlUserType.ActivateInstance()
       at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter)
       at Universal.App.OnLaunched(LaunchActivatedEventArgs e)
  InnerException: 

```

**Comment by EgorBo** [comment]
Fixed

**Comment by tripolskypetr** [comment]
I have a same bug. It is not fixed

**Comment by davejmurphy** [comment]
@tripolskypetr Try to move your call to UrhoSurface.Run<T>() to the loaded event of the page. If it's called too early it throws the same exception (coming from SDL_CreateWindow). I think the size and position of the surface needs to be known before it's used.
