### ISSUE TITLE
XamarinForms  UWP Null error exception at Urho.UWP.UrhoSurface.CopyEmbeddedResourceToLocalFolder

### ISSUE THREAD

**Issue by juanfranblanco** [xamarin/urho#152]
On a new Xamarin.Forms UWP application when first loaded a null exception is thrown:

   at Urho.UWP.UrhoSurface.CopyEmbeddedResourceToLocalFolder(String embeddedResource, String destFileName)
   at Urho.UWP.UrhoSurface.Run(Type appType, String[] customAssetsPaks, ApplicationOptions opt)
   at Urho.Forms.UwpSurfaceRenderer.UrhoLauncher(Type type, ApplicationOptions opts)
   at Urho.Forms.UrhoSurface.<Show>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SamplyGame.UrhoPage.<StartUrhoApp>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SamplyGame.UrhoPage.<OnAppearing>d__14.MoveNext()

This error happens only when loading the project for the first time, and afterwards, the application will hang when launched again.

**Comment by juanfranblanco** [comment]
I think it is due to this:

https://github.com/xamarin/urho/blob/master/Bindings/UWP/UrhoSurface.cs#L54

and this 

![image](https://cloud.githubusercontent.com/assets/562371/18431601/8d6125ba-78d5-11e6-8011-b3bfffd1ded2.png)

**Comment by juanfranblanco** [comment]
Yes copying the CoreData.pak to the LocalState folder allows to load the gamey sample, but surface is mostly black only ui controls added.

**Comment by EgorBo** [comment]
Thanks @juanfranblanco I'll fix that.
