### ISSUE TITLE
Viewport can not be set to the Renderer twice

### ISSUE THREAD

**Issue by gleblebedev** [xamarin/urho#283]
I have a scenario with 2 viewports involved. I would like to call `Renderer.SetViewport` with one, then with another, and then with the first one again. Unfortunately it produces an issue. I guess it's connected to reference counting in native code and how references tracked in a managed code.

```
An unhandled exception of type 'System.AccessViolationException' occurred in TestViewportChange.dll
```

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```
   at Urho.Renderer.Renderer_SetViewport(IntPtr handle, UInt32 index, IntPtr viewport)
   at Sample.HandleKeyUp(KeyUpEventArgs obj) in E:\Temp\TestViewportChange\Scripts\Sample.cs:line 83
   at Urho.UrhoEventAdapter`1.<>c__DisplayClass5_0.<AddManagedSubscriber>b__0(TEventArgs args)
   at Urho.Input.<>c__DisplayClass213_0.<SubscribeToKeyUp>b__0(IntPtr x)
   at Urho.UrhoObject.ObjectCallback(IntPtr data, Int32 stringHash, IntPtr variantMap)
   at Urho.Application.Application_Run(IntPtr handle)
   at TestViewportChange.Program.Main(String[] args) in E:\Temp\TestViewportChange\VisualStudio\WinForms\Program.cs:line 33
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by migueldeicaza** [comment]
That sounds like a valid theory.

You can try debugging this with your existing code by calling the `Refs` method before and after to see when the reference count on the underlying object is changing.

If the reference is dropping, use `AddRef` on it.

**Comment by EgorBo** [comment]
Moved to https://github.com/xamarin/urho/issues/302
