### ISSUE TITLE
[UWP] Failed to create sample state and related errors

### ISSUE THREAD

**Issue by deakjahn** [xamarin/urho#356]
I have a scene with a model where I want to periodically change the material of the model upon user interaction. Sometimes it works but at least in half of the cases I get an error message from Urho itself, or even from the underlying Win DirectX implementation. In some cases, the whole screen turns black for a second. The reason for mentioning it here is that I can't seem to be able to at least isolate and report the error in UrhoSharp cleanly.

The error is:

    11/25/2018 11:28:11 +00:00 - Failed to create sampler state (HRESULT 887a0005). You can omit this exception by subscribing to Urho.Application.UnhandledException event and set Handled property to True.
    ApplicationOptions: args -w -x 737 -y 826 -p "CoreData" -touch -hd -landscape -portrait 
    11/25/2018 11:28:11 +00:00 - Unhandled error -- NullReferenceException: Object reference not set to an instance of an object.
       at MyUrhoApplication.<>c.<.cctor>b__17_0(Object s, UnhandledExceptionEventArgs e)
       at Urho.Application.ThrowUnhandledException(Exception exc)
       at Urho.Runtime.OnNativeCallback(CallbackType type, IntPtr target, IntPtr param1, Int32 param2, String param3)
       at Urho.Engine.Engine_RunFrame(IntPtr handle)
       at Urho.UWP.UrhoSurface.<>c__DisplayClass11_0.<<Run>b__0>d.MoveNext()

The first comes in via the `UnhandledException` exception handler but the second one brings down my app.

I set up the scene the usual way, no problem with that and the first image always appears with the texture-based material all right, so that's not part of the issue. I change the material with this function:

    public void Redraw(byte[] bitmap) {
      try {
        using (var texture = new Texture2D(Context))
          if (texture != null)
            using (var buffer = new MemoryBuffer(bitmap))
              if (texture.Load(buffer)) {
                model.Material?.Dispose();

                var material = new Material();
                material.SetTexture(TextureUnit.Diffuse, texture);
                material.SetTechnique(0, CoreAssets.Techniques.Diff, 0, 0);
                model.Material = material;

                scene.Update(0f);
              }
      }
      catch (Exception e) {
        Logger.Log.Error(e.Message, e);
      }
    }

As you can see, it's in a `try-catch`, still I get the exception. It refers to the app constructor which is completely empty in my case but, of course, calls the overridden one:

    public MyUrhoApplication(ApplicationOptions options = null)
      : base(options) {
    }

First, I can't see the obvious culprit in the UrhoSharp source code. Second, perhaps more importantly, I can't understand why this constructor is called again later in the process, not when I set it up but when I merely change the material and update the scene.

**Comment by deakjahn** [comment]
Just an unrelated idea that came to mind: you shouldn't add the "You can omit this exception" text in `Runtime.OnNativeCallback()`. Move it to `Urho.Application.ThrowUnhandledException()` and only add it to the error message if `UnhandledException` is null. If the user did subscribe to this event, there is no need to inform them that they can subscribe to it.

**Comment by utekai** [comment]
Ensure you're doing this from the main thread.

InvokeOnMain or InvokeOnMainAsync

Messing with materials is a main thread activity. 

This might not be your problem, but I've seen it throw errors like you point out, which don't necessarily correlate to what's happening. The reason I point this out is because of the screen blacking out that you mentioned, there is a reason for that.

Another possible issue is Actions running on the node you're changing the material of, and they are using the old material and have a reference to it, but you came along and changed the material, and urho didn't respect their reference, which brings up the AddRef() call that can help if you don't want to remove the actions before changing materials.

Also, some of those errors like you point out can be e.Handled=true, and life goes on. But you have to specifically do it. So maybe you're not yet chasing the right error for your material. In my experience, changing the materials is very problematic, but in general works, you have to have very good scene management. Alternatively, other patterns work very well, without problems. Such as enabling one node, and disabling a second, instead of doing a material changeover. Or use Actions and do a Hide() on one, and a Show() on the other.

**Comment by utekai** [comment]
> this constructor is called again later 

Probably not the constructor, but it is looking for the Application.UnhandledException handler. That's where you e.Handled=true the unhandled exceptions, and attempt to move on.
