### ISSUE TITLE
"Failed to resolve assembly" errors

### ISSUE THREAD

**Issue by deakjahn** [xamarin/urho#361]
1.9.67 gives *Failed to resolve assembly: UrhoForms, Version=0.0.0.0* errors. 1.8.93 worked flawlessly.

**Comment by EgorBo** [comment]
@deakjahn could you please share more details - which version of XF, what platforms cause this issue. E.g. your XF android projects should be at least monodroid81 target, etc

**Comment by deakjahn** [comment]
XF: latest, 3.4.0.1008975
Nothing else changed, just Urho updated from 1.8.93 to 1.9.67.

There are actually two errors, the one noted above references the namespace in the XAML file (   xmlns:urho="clr-namespace:Urho.Forms;assembly=Urho.Forms").

The other comes from the UWP project:

Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: Urho.Forms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.'

**Comment by deakjahn** [comment]
Android also has problems:

Warning	NU1701	Package 'UrhoSharp.Forms 1.8.93' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by EgorBo** [comment]
@deakjahn can I see your csprojs? I suspect you have some old targetframeworks, e.g. as I said - Android must be >=monodroid81

**Comment by deakjahn** [comment]
Android 9.0, support libraries just changed to 28 very recently. Are we speaking about this version (because I couldn't find the actual name monodroid anywhere). I suspect so, so in this case, it's long switched to 9.0.

**Comment by EgorBo** [comment]
@deakjahn those are API levels, what I mean is e.g.
`<TargetFrameworkVersion>v8.1</TargetFrameworkVersion>` or `monodroid81`

**Comment by deakjahn** [comment]
It's been staying at

    <TargetFrameworkVersion>v9.0</TargetFrameworkVersion>

since the discovery of the Americas. ;-)

**Comment by laheller** [comment]
@EgorBo 

Another problem is at an empty windows **console app**, when you try to add **1.9.67**

> Failed to add reference to 'mono-urho'.
>   Please make sure that the file is accessible, and that it is a valid assembly or COM component.
>

**Comment by deakjahn** [comment]
Just to mention that nothing has changed. Brand new installation of Windows and Visual Studio 15.9.7, Xamarin Forms 3.5.0.129452, UrhoSharp.Forms 1.9.76, error message:

    Failed to resolve assembly: 'Urho.Forms, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

Projects: UWP, Android 28.0.0.1 (targeting 9.0)

As soon as I downgrade Urho, everything runs perfectly with the very same environment.

**Comment by MartinOrtiz** [comment]
I have Windows 10, VS 2019. 
I create new Xamarin forms project. (iOS, Android, UWP)
I did nuGet of UrhoSharp-ns2-preview (version 2.0.6)

I copied sample code into the UWP project (the one with all the demo samples).
It builds, but I get the same error.
When I run it, and click on an example it crashes.

**Comment by MartinOrtiz** [comment]
here is download link to project
https://app.box.com/s/odlj7mwjldo59bkmrwzi4ap2wc9xy8hn

**Comment by MartinOrtiz** [comment]
Here is exception....(I thought I got the "unresolved" exception at some point..)
In Samples.cs
On this line of code:
    protected Sample(ApplicationOptions options) : base(options) { }

System.Exception
  HResult=0x80131500
  Message=Implementation assembly (iOS, Android or Desktop) is not referenced
  Source=UrhoSharp
  StackTrace:
   at Urho.UrhoPlatformInitializer.DefaultInit()
   at Urho.Context..ctor()
   at Urho.Application..ctor(ApplicationOptions options)
   at Urho.Samples.Sample..ctor(ApplicationOptions options) in C:\Users\martin\Downloads\UrhoApp2\UrhoApp2\UrhoApp2\UrhoApp2\Core\Sample.cs:line 48
   at Urho.Samples.AnimatingScene..ctor(ApplicationOptions options) in C:\Users\martin\Downloads\UrhoApp2\UrhoApp2\UrhoApp2\UrhoApp2\Core\05_AnimatingScene\AnimatingScene.cs:line 30

**Comment by MartinOrtiz** [comment]
If you get errors during build, doing a rebuild seems to clear it up.

**Comment by MartinOrtiz** [comment]
Error happens when I select a demo in the list on the left (any of them)

<img width="601" alt="uj2" src="https://user-images.githubusercontent.com/11322523/57092691-f4117a80-6cd9-11e9-8885-e93a8ac23be1.png">

**Comment by mdbill** [comment]
> (xmlns:urho="clr-namespace:Urho.Forms;assembly=Urho.Forms").

I had success by changing Urho to UrhoSharp...
xmlns:urho="clr-namespace:Urho.Forms;assembly=**UrhoSharp**.Forms"
